---
- hosts: ios


  tasks:
  
  - name: get the current aaa configs
    ios_command:
      commands:
        - "show running-config full | include aaa"
    register: get_config

  - debug: var=get_config.stdout_lines

  - name: set aaa configs
    with_items: "{{ aaa_configs }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_aaa

  - name: remove aaa configs
    when: "(get_config.stdout_lines[0] != '') and (item not in aaa_configs)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_aaa
    ios_config:
      lines:
        - "no {{ item }}"

  - name: servicenow_network_tickets
    when: set_aaa.changed or remove_aaa.changed 
    import_role:
      name: servicenow_network_tickets
