---
- hosts: ios


  tasks:
  
  - name: get the current snmp-server config
    ios_command:
      commands:
        - "show running-config full | include snmp-server"
    register: get_config

  - debug: var=get_config.stdout_lines

  - name: set snmp-server configs
    with_items: "{{ snmp_server }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_snmp

  - name: remove snmp-server configs
    when: "(get_config.stdout_lines[0] != '') and (item not in snmp_server)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_snmp
    ios_config:
      lines:
        - "no {{ item }}"

  - name: debug set_snmp
    debug:
      var: set_snmp

#  - name: display added commands
#    when: "set_snmp.changed"
#    with_items: "{{ set_snmp.results }}"
#    debug:
#      var: set_snmp.item.commands
#    loop_control:
#      label: "{{ set_snmp }}"

#  - name: display removed commands
#    when: remove_snmp.changed
#    debug:
#      msg: "{{ remove_snmp }}"

  - name: servicenow_network_tickets
    when: set_snmp.changed or remove_snmp.changed 
    import_role:
      name: servicenow_network_tickets
